export default establishmentTypes = [
    { label: 'Academia', value: 'ACADEMIA' },
    { label: 'Aeroporto', value: 'AEROPORTO' },
    { label: 'Banco', value: 'BANCO' },
    { label: 'Clínica', value: 'CLINICA' },
    { label: 'Diversão', value: 'DIVERSAO' },
    { label: 'Escola', value: 'ESCOLA' },
    { label: 'Faculdade', value: 'FACULDADE' },
    { label: 'Farmácia', value: 'FARMACIA' },
    { label: 'Hospital', value: 'HOSPITAL' },
    { label: 'Hotel', value: 'HOTEL' },
    { label: 'Loja', value: 'LOJA' },
    { label: 'Mercado', value: 'MERCADO' },
    { label: 'Motel', value: 'MOTEL' },
    { label: 'Museu', value: 'MUSEU' },
    { label: 'Parque', value: 'PARQUE' },
    { label: 'Prédio Público', value: 'PREDIO_PUBLICO' },
    { label: 'Restaurante', value: 'RESTAURANTE' },
    { label: 'Rodoviária', value: 'RODOVIARIA' },
    { label: 'Salão de Beleza', value: 'SALAO_DE_BELEZA' },
    { label: 'Shopping', value: 'SHOPPING' },
    { label: 'Outro', value: 'OUTRO' },
];